# Generated by Django 5.0.1 on 2024-02-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='SignedUser',
        ),
    ]
