# Generated by Django 5.0.1 on 2024-02-14 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_users_signeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeduser',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
