# Generated by Django 5.0.1 on 2024-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signeduser',
            name='id',
        ),
        migrations.AlterField(
            model_name='signeduser',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
