# Generated by Django 5.0.2 on 2024-03-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_title',
            new_name='title',
        ),
    ]
